//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smart_education_center.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Choice
    {
        public int Id { get; set; }
        public Nullable<int> QuestionId { get; set; }
        public string ChoiceLabel { get; set; }
        public Nullable<int> ChoiceNumber { get; set; }
        public Nullable<int> IsActive { get; set; }
        public Nullable<int> IsDeleted { get; set; }
    
        public virtual Question Question { get; set; }
    }
}
