//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smart_education_center.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestEntry
    {
        public int Id { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<int> TestID { get; set; }
        public Nullable<System.DateTime> EntryDateTime { get; set; }
        public string Token { get; set; }
        public Nullable<System.DateTime> TokenExpireTime { get; set; }
        public Nullable<int> TotalMarks { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual Test Test { get; set; }
    }
}
